[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@supabase/supabase-js", "node-fetch"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"